
- name create transite directories
  file:
    path '{{ item }}'
    mode 0755
    state directory
  with_items:
  - '{{ transite_home_dir }}'
  - '{{ msp_cert_dir }}'
  - '{{ transite_log_dir }}'
  
  - name download transite startup
    get_url:
      url: '{{ transite_startup_source }}'
      dest: '{{transite_home_dir }}'/msp_tpw_was_m00.tar.gz'
      
    - unarchive src= '{{transite_home_dir }}'/msp_tpw_was_m00.tar.gz' dest=/prod/msp/domains/tpw_domains/qas01 copy=no
      sudo: True
      
      - name: Set Environment variable
        sudo: True
        copy: src=setenvnew.sh dest='{{transite_home_dir }}/msp_tpw_was_m00/bin/setenv.sh' mode=0755
        
        - shell: '{{transite_home_dir }}/msp_tpw_was_m00/bin/setenv.sh'
          sudo: yes
          remote_user: ec2-user
          
        - name: Configure Start script
          sudo: True
          copy: src=startmsp_tpw_qasnew.sh dest='{{transite_home_dir }}/msp_tpw_was_m00/startmsp_tpw_qas_m00.sh'
          
          shell: '{{transite_home_dir }}/msp_tpw_was_m00/startmsp_tpw_qas_m00.sh'
          sudo: yes
          remote_user: ec2-user
          
          
