DEPLOY_ENV=bvt
DEPLOY_NUMBER=13
DEPLOY_LOCATION=de
DEPLOY_ID=${DEPLOY_ENV}${DEPLOY_NUMBER}
JAVA_HOME="/usr/lib/jvm/jre""
JAVA_OPTS1=" -Xmx2048m -Xms1024m -XX:NewSize=256m -XX:MaxNewSize=256m"
JAVA_OPTS2=" -XX:PermSize=128m -XX:MaxPermSize=256m"
JAVA_OPTS3=" -DApplicationPropertyFileName=tpw.${DEPLOY_ENV}.${DEPLOY_LOCATION}.${DEPLOY_NUMBER}.lnx.properties"
export JAVA_HOME
export JAVA_OPTS="${JAVA_OPTS1}${JAVA_OPTS2}${JAVA_OPTS3}"
export DEPLOY_ENV DEPLOY_NUMBER DEPLOY_ID DEPLOY_LOCATION 
