HOST_NAME=`hostname`
DOMAIN_IDENTIFIER=qas01
SERVER_NAME=msp_tpw_qas 
SERVER_INSTANCE=00
DEPLOY_ENV=qa.qa2
DEPLOY_NUMBER=1
DEPLOY_LOCATION=mn
DEPLOYE_IDENTIFIER=${DEPLOY_LOCATION}${DEPLOY_NUMBER}
PROBE_NAME=${HOST_NAME}_${DOMAIN_IDENTIFIER}_${SERVER_NAME}
PROBE_GROUP=$DOMAIN_IDENTIFIER
JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79.x86_64/jre
JAVA_OPTS="-Xmx2048m -Xms1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m"
CATALINA_HOME=/usr/share/tomcat
CATALINA_BASE=/prod/msp/domains/tpw_qas/qas01/msp_tpw_qas
CATALINA_OPTS=-DApplicationPropertyFileName=tpw.${DEPLOY_ENV}.${DEPLOY_LOCATION}.${DEPLOY_NUMBER}.lnx.properties

export JAVA_HOME JAVA_OPTS CATALINA_OUT CATALINA_HOME CATALINA_BASE CATALINA_OPTS
export 
exec $CATALINA_HOME/bin/catalina.sh start
